/* Vector PDF renderer. Bundled libraries and fonts: no external CDN. */
(function(global){
  let loading;
  function script(src){return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=()=>{s.remove();reject(Error('Nie można wczytać składników PDF. Spróbuj ponownie.'))};document.head.appendChild(s)})}
  async function ready(){if(!loading)loading=(async()=>{if(!global.PDFLib)await script('/pdf-assets/pdf-lib.js');if(!global.fontkit)await script('/pdf-assets/fontkit.js');const fonts=await Promise.all(['regular','bold'].map(async n=>{const r=await fetch('/pdf-assets/'+n+'.ttf');if(!r.ok)throw Error('Nie można wczytać czcionki PDF');return r.arrayBuffer()}));return fonts})().catch(e=>{loading=null;throw e});return loading}
  function canvas(){const commands=[],measure=document.createElement('canvas').getContext('2d');const ctx={font:'16px Arial',fillStyle:'#000',strokeStyle:'#000',lineWidth:1,textAlign:'left',textBaseline:'top',measureText(t){measure.font=this.font;return measure.measureText(String(t))},fillRect(x,y,w,h){commands.push({op:'fill',x,y,w,h,color:this.fillStyle})},strokeRect(x,y,w,h){commands.push({op:'stroke',x,y,w,h,color:this.strokeStyle,lineWidth:this.lineWidth})},fillText(text,x,y,maxWidth){commands.push({op:'text',text:String(text),x,y,maxWidth,font:this.font,color:this.fillStyle,align:this.textAlign})}};return{canvas:{commands},ctx,logicalW:1240,logicalH:1754,scale:1}}
  function rgb(hex){hex=String(hex).replace('#','');if(hex.length===3)hex=hex.split('').map(x=>x+x).join('');return global.PDFLib.rgb(parseInt(hex.slice(0,2),16)/255,parseInt(hex.slice(2,4),16)/255,parseInt(hex.slice(4,6),16)/255)}
  async function bytes(pages){const buffers=await ready(),lib=global.PDFLib,doc=await lib.PDFDocument.create();doc.registerFontkit(global.fontkit);const fonts=await Promise.all(buffers.map(b=>doc.embedFont(b,{subset:true})));const k=595.28/1240,H=841.89;doc.setTitle('Łowcy Methodowcy');doc.setCreator('Łowcy Methodowcy — PDF wektorowy');
    for(const input of pages){const page=doc.addPage([595.28,H]);for(const c of input.commands){if(c.op==='text'){if(!c.text)continue;const match=c.font.match(/([\d.]+)px/),size=Number(match?.[1]||16),bold=/\b(?:[6-9]00|1000|bold)\b/.test(c.font),font=fonts[bold?1:0];let pt=size*k;const width=font.widthOfTextAtSize(c.text,pt);if(c.maxWidth&&width>c.maxWidth*k)pt*=c.maxWidth*k/width;const actual=font.widthOfTextAtSize(c.text,pt);let x=c.x*k;if(c.align==='center')x-=actual/2;else if(c.align==='right')x-=actual;page.drawText(c.text,{x,y:H-c.y*k-font.heightAtSize(pt,{descender:false}),font,size:pt,color:rgb(c.color)})}else{const opts={x:c.x*k,y:H-(c.y+c.h)*k,width:c.w*k,height:c.h*k};if(c.op==='fill')opts.color=rgb(c.color);else{opts.borderColor=rgb(c.color);opts.borderWidth=c.lineWidth*k}page.drawRectangle(opts)}}}return doc.save()}
  async function download(pages,filename){try{const data=await bytes(pages),blob=new Blob([data],{type:'application/pdf'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000)}catch(e){if(typeof msg==='function')msg('PDF: '+e.message,'bad');else throw e}}
  global.LowcyPDF={canvas,bytes,download};
})(typeof window==='undefined'?globalThis:window);
