name = "matchthis"
main = "src/index.js"
compatibility_date = "2026-10-08"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "matchthis-db"
database_id = "3e36a4dd-530a-4e6e-a819-2b5b3e6539da"
